# Secret
---
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secrets.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
