apiVersion: v2
name: app
description: A Helm chart for Go application on Kubernetes
type: application

version: 1.0.0
appVersion: "1.0.0"

keywords:
  - app
  - go
  - service
  - kubernetes

maintainers:
  - name: Vishal
    email: vishal267@ymail.com

dependencies: []

# Helm chart conventions
kubeVersion: ">=1.24.0"

# Chart metadata
icon: ""
deprecated: false
